# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Push a new iOS beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    setup_ci

    app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['API_ISSUER_ID'],
      key_content: ENV["API_KEY_CONTENT"]
    )

    sync_code_signing(type: "appstore")

    cocoapods(repo_update: true, podfile: "./ios")
    
    build_app(workspace: "./ios/yourgreatapp.xcworkspace", scheme: ENV["SCHEME"])
    
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :android do
  desc "Upload a beta version"
  lane :beta do
    keystorePath = File.join(Dir.pwd, "..", "android", "app.keystore")

    gradle(
      project_dir: 'android',
      task: 'bundle',
      FLAVOR: ENV['FLAVOR'],
      properties: {
        "android.injected.signing.store.file" => keystorePath,
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )

    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_changelogs: true,
      aab_paths: ["app/build/outputs/bundle/#{ENV['FLAVOR'].downcase}Release/app-#{ENV['FLAVOR'].downcase}-release.aab"],
      release_status: 'draft',
    )
  end
end
